### ISSUE TITLE
Error bin/setup

### ISSUE THREAD

**Issue by socialwarespace** [nuita/nuita#120]
== Preparing database ==
rails aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/var/www/www-root/data/www/huita/nuita/config/initializers/omniauth.rb:2:in `block in <main>'
/usr/share/rvm/gems/ruby-2.6.2/gems/rack-2.0.8/lib/rack/builder.rb:55:in `instance_eval'
/usr/share/rvm/gems/ruby-2.6.2/gems/rack-2.0.8/lib/rack/builder.rb:55:in `initialize'
/usr/share/rvm/gems/ruby-2.6.2/gems/omniauth-1.9.0/lib/omniauth/builder.rb:6:in `initialize'
/usr/share/rvm/gems/ruby-2.6.2/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:37:in `new'
/usr/share/rvm/gems/ruby-2.6.2/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:37:in `build'
/usr/share/rvm/gems/ruby-2.6.2/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:101:in `block in build'
/usr/share/rvm/gems/ruby-2.6.2/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:101:in `each'
/usr/share/rvm/gems/ruby-2.6.2/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:101:in `inject'
/usr/share/rvm/gems/ruby-2.6.2/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:101:in `build'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/engine.rb:510:in `block in app'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/engine.rb:506:in `synchronize'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/engine.rb:506:in `app'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/var/www/www-root/data/www/huita/nuita/config/environment.rb:5:in `<main>'
/usr/share/rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/rvm/gems/ruby-2.6.2/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/rvm/gems/ruby-2.6.2/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rvm/gems/ruby-2.6.2/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/usr/share/rvm/gems/ruby-2.6.2/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
/usr/share/rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/rvm/gems/ruby-2.6.2/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/rvm/gems/ruby-2.6.2/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rvm/gems/ruby-2.6.2/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/var/www/www-root/data/www/huita/nuita/bin/rails:9:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.6.2/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/usr/share/rvm/gems/ruby-2.6.2/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/usr/share/rvm/gems/ruby-2.6.2/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/usr/share/rvm/gems/ruby-2.6.2/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/usr/share/rvm/gems/ruby-2.6.2/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.6.2/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/usr/share/rvm/gems/ruby-2.6.2/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/var/www/www-root/data/www/huita/nuita/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config => environment
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==

**Comment by socialwarespace** [comment]
fixed
