### ISSUE TITLE
外部キー制約のせいで既存dbをdropできない……？

### ISSUE THREAD

**Issue by kypkyp** [nuita/nuita#249]
Docker内で```rails db:setup```しようとして失敗したので、念の為にエラー内容を残しておきます
外部キー制約によるもの？らしいけど、該当テーブルへの変更は一切加わってないので、環境的な何かかもしれない？

ちなみにDBコンテナ(ex: ```nuita_db_1```)に入ってMySQLのコンソールから
`set foreign_key_checks = 0;` 
ってやったらエラー消えました

```
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot drop table 'links' referenced by a foreign key constraint 'fk_rails_d74805ffa8' on table 'nweet_links'.: DROP TABLE IF EXISTS `links` CASCADE
/app/vendor/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/app/vendor/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/app/vendor/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/app/vendor/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:340:in `drop_table'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:308:in `create_table'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:871:in `block in method_missing'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:840:in `block in say_with_time'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:840:in `say_with_time'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:860:in `method_missing'
/app/db/schema.rb:51:in `block in <main>'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/schema.rb:50:in `instance_eval'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/schema.rb:50:in `define'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/schema.rb:46:in `define'
/app/db/schema.rb:13:in `<main>'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `block in load'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:245:in `load_schema'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:266:in `block in load_schema_current'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:313:in `each'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:265:in `load_schema_current'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/railties/databases.rake:258:in `block (3 levels) in <main>'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/railties/databases.rake:262:in `block (3 levels) in <main>'
/app/vendor/bundle/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/app/vendor/bundle/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/app/vendor/bundle/gems/railties-5.2.4.3/lib/rails/command.rb:48:in `invoke'
/app/vendor/bundle/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<main>'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/app/bin/rails:9:in `<top (required)>'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/app/vendor/bundle/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/app/bin/spring:15:in `<top (required)>'
/app/bin/rails:3:in `load'
/app/bin/rails:3:in `<main>'

Caused by:
Mysql2::Error: Cannot drop table 'links' referenced by a foreign key constraint 'fk_rails_d74805ffa8' on table 'nweet_links'.
/app/vendor/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/app/vendor/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/app/vendor/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/app/vendor/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:340:in `drop_table'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:308:in `create_table'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:871:in `block in method_missing'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:840:in `block in say_with_time'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:840:in `say_with_time'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:860:in `method_missing'
/app/db/schema.rb:51:in `block in <main>'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/schema.rb:50:in `instance_eval'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/schema.rb:50:in `define'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/schema.rb:46:in `define'
/app/db/schema.rb:13:in `<main>'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `block in load'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:245:in `load_schema'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:266:in `block in load_schema_current'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:313:in `each'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:265:in `load_schema_current'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/railties/databases.rake:258:in `block (3 levels) in <main>'
/app/vendor/bundle/gems/activerecord-5.2.4.3/lib/active_record/railties/databases.rake:262:in `block (3 levels) in <main>'
/app/vendor/bundle/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/app/vendor/bundle/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/app/vendor/bundle/gems/railties-5.2.4.3/lib/rails/command.rb:48:in `invoke'
/app/vendor/bundle/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<main>'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/app/vendor/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/app/vendor/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/app/bin/rails:9:in `<top (required)>'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/app/vendor/bundle/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/app/vendor/bundle/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/app/bin/spring:15:in `<top (required)>'
/app/bin/rails:3:in `load'
/app/bin/rails:3:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

**Comment by ahis1503** [comment]
おそらくデータがある状態でsetupを実行したことでdropが実行されてるので、動作自体は正常だと思いますが、たぶん開発時には不要なので、mysqlコンテナに設定ファイルを配置したほうがよいかもです
